THEOS_DEVICE_IP=127.0.0.1
THEOS_DEVICE_PORT=2222

include theos/makefiles/common.mk

export GO_EASY_ON_ME=1

TWEAK_NAME = appslide
appslide_FILES = Tweak.xm
appslide_FRAMEWORKS = UIKit CoreGraphics QuartzCore

include $(THEOS_MAKE_PATH)/tweak.mk
