TWEAK_NAME = no-folder-badge
no-folder-badge_OBJCC_FILES = Tweak.mm
no-folder-badge_FRAMEWORKS = UIKit QuartzCore CoreGraphics

include framework/makefiles/common.mk
include framework/makefiles/tweak.mk
