include theos/makefiles/common.mk

TWEAK_NAME = ColloquyTabComplete
ColloquyTabComplete_FILES = Tweak.xm
ColloquyTabComplete_FRAMEWORKS = UIKit
ColloquyTabComplete_PRIVATE_FRAMEWORKS = GraphicsServices

include $(THEOS_MAKE_PATH)/tweak.mk
